### ISSUE TITLE
Need proper namespase on PDO object in AtlasContainer

### ISSUE THREAD

**Issue by jelofson** [cadrephp/AtlasOrm.DebugBar.Bridge#3]
in `Cadre\AtlasOrmDebugBarBridge\AtlasContainer`, when passing an instance of ExtendedPdo as `$arg[0]`, the driver is obtained via `$driver = $extendedPdo->getAttribute(PDO::ATTR_DRIVER_NAME);`.  (see line 18)

However, an error occurs `Error: Class 'Cadre\AtlasOrmDebugBarBridge\PDO' not found `. 

Just add a `use PDO` at about line 6 and that will solve it. 

Seems too small for a PR, but if you would rather, I can do that too.

**Comment by andrewshell** [comment]
@jelofson Thanks for reporting this!

Turns out I didn't have tests for parts of AtlasContainer.  Even after adding `use PDO;` it still didn't work. Had to wrap the passed in PDO object in TraceablePDO as well.

This is all fixed and working in v1.1.1

**Comment by jelofson** [comment]
Ok. Awesome! Thanks for doing that so quickly.

Jon
